-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 22:06:17 2023
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GOGUS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GOGUS_DEV` ;

-- -----------------------------------------------------
-- Table `GOGUS`.`LIVRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GOGUS_DEV`.`LIVRO` ;

CREATE TABLE IF NOT EXISTS `GOGUS_DEV`.`LIVRO` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(13) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(100) NULL,
  `edicao` INT NOT NULL,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE,
  UNIQUE INDEX `id_livro_UNIQUE` (`id_livro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GOGUS`.`AUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GOGUS_DEV`.`AUTOR` ;

CREATE TABLE IF NOT EXISTS `GOGUS_DEV`.`AUTOR` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `sobrenome` VARCHAR(60) NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GOGUS`.`EDITORA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GOGUS_DEV`.`EDITORA` ;

CREATE TABLE IF NOT EXISTS `GOGUS_DEV`.`EDITORA` (
  `id_EDITORA` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_EDITORA`),
  UNIQUE INDEX `id_EDITORA_UNIQUE` (`id_EDITORA` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GOGUS`.`GENERO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GOGUS_DEV`.`GENERO` ;

CREATE TABLE IF NOT EXISTS `GOGUS_DEV`.`GENERO` (
  `id_Genero` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Genero`),
  UNIQUE INDEX `id_Genero_UNIQUE` (`id_Genero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GOGUS`.`GENERO_LIVRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GOGUS_DEV`.`GENERO_LIVRO` ;

CREATE TABLE IF NOT EXISTS `GOGUS_DEV`.`GENERO_LIVRO` (
  `id_GENERO_LIVRO` INT NOT NULL AUTO_INCREMENT,
  `LIVRO_ISBN` VARCHAR(13) NOT NULL,
  `GENERO_id_Genero` INT NOT NULL,
  PRIMARY KEY (`id_GENERO_LIVRO`, `LIVRO_ISBN`, `GENERO_id_Genero`),
  INDEX `fk_GENERO_LIVRO_LIVRO1_idx` (`LIVRO_ISBN` ASC) VISIBLE,
  INDEX `fk_GENERO_LIVRO_GENERO1_idx` (`GENERO_id_Genero` ASC) VISIBLE,
  CONSTRAINT `fk_GENERO_LIVRO_LIVRO1`
    FOREIGN KEY (`LIVRO_ISBN`)
    REFERENCES `GOGUS`.`LIVRO` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GENERO_LIVRO_GENERO1`
    FOREIGN KEY (`GENERO_id_Genero`)
    REFERENCES `GOGUS`.`GENERO` (`id_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GOGUS`.`AUTOR_LIVRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GOGUS_DEV`.`AUTOR_LIVRO` ;

CREATE TABLE IF NOT EXISTS `GOGUS_DEV`.`AUTOR_LIVRO` (
  `id_AUTOR_LIVRO` INT NOT NULL AUTO_INCREMENT,
  `LIVRO_ISBN` VARCHAR(13) NOT NULL,
  `AUTOR_id_Autor` INT NOT NULL,
  PRIMARY KEY (`id_AUTOR_LIVRO`, `LIVRO_ISBN`, `AUTOR_id_Autor`),
  INDEX `fk_AUTOR_LIVRO_LIVRO1_idx` (`LIVRO_ISBN` ASC) VISIBLE,
  INDEX `fk_AUTOR_LIVRO_AUTOR1_idx` (`AUTOR_id_Autor` ASC) VISIBLE,
  CONSTRAINT `fk_AUTOR_LIVRO_LIVRO1`
    FOREIGN KEY (`LIVRO_ISBN`)
    REFERENCES `GOGUS`.`LIVRO` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTOR_LIVRO_AUTOR1`
    FOREIGN KEY (`AUTOR_id_Autor`)
    REFERENCES `GOGUS`.`AUTOR` (`id_Autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GOGUS`.`LIVRO_EDITORA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GOGUS_DEV`.`LIVRO_EDITORA` ;

CREATE TABLE IF NOT EXISTS `GOGUS_DEV`.`LIVRO_EDITORA` (
  `id_LIVRO_EDITORA` INT NOT NULL AUTO_INCREMENT,
  `LIVRO_ISBN` VARCHAR(13) NOT NULL,
  `ID_EDITORA` INT NOT NULL,
  PRIMARY KEY (`id_LIVRO_EDITORA`, `LIVRO_ISBN`, `ID_EDITORA`),
  INDEX `fk_LIVRO_EDITORA_LIVRO1_idx` (`LIVRO_ISBN` ASC) VISIBLE,
  INDEX `fk_LIVRO_ID_EDITORA1_idx` (`ID_EDITORA` ASC) VISIBLE,
  CONSTRAINT `fk_LIVRO_EDITORA_LIVRO1`
    FOREIGN KEY (`LIVRO_ISBN`)
    REFERENCES `GOGUS`.`LIVRO` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRO_ID_EDITORA1`
    FOREIGN KEY (`ID_EDITORA`)
    REFERENCES `GOGUS`.`EDITORA` (`id_EDITORA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



